### PR TITLE
My cart screen

### PR DESCRIPTION
**Pull request by zoef-yt**
Added just the layout of the cart screen and fixed a CSS issue. It's a UI update.
Preview link:- [CartPage](https://deploy-preview-7--need-games-zoef.netlify.app/)

### Things to check
- [x]  Ui 

### Things not to check:
- [ ] The functionality of the app

### CODE REVIEW

**Review by itsmebipul00 — APPROVED** [review]
Good to merge, nice work

**Review by humzahasan — APPROVED** [review]
UI Suggestion : While on cart page, since it's final checkout i believe showing all the prodcuts in cart on the page is better than having it inside scrollable div. 

Code looks good to merge!

**Review by itsmebipul00 — COMMENTED** [review]
You could remove the comments

**Comment by zoef-yt** [comment]
> UI Suggestion : While on cart page, since it's final checkout i believe showing all the prodcuts in cart on the page is better than having it inside scrollable div.
> 
> Code looks good to merge!

Thanks for the suggestion will look into it.

**Pull request merged**
