### PR TITLE
FEAT: Added add to cart and wishlist with mockbee

### PR DESCRIPTION
**Pull request by zoef-yt**
In this pr, I Fixed the functionality of the wishlist and added the "add to cart" functionality

[Live preview](https://deploy-preview-19--need-games-zoef.netlify.app/)
There are some comments for future reference.

### CODE REVIEW

**Review by tonymike99 — APPROVED** [review]
Hey Zoef!
Great UI! Neatly written code..
You've added "Commented out to test" at places which is nice.
You might want to do a small bug fix for the cart handling later on.
Everything else works fine 👍

Screenshot_15

**Review by iRohitGaur — APPROVED** [review]
Nice work. UI is great. Good to merge 👍🏻

**Review by dev-prabhat — CHANGES_REQUESTED** [review]
Code is fine and readable just need to debug your code as per mentioned in suggestion

**Comment by devAmlan** [comment]
Everything looks good, It's good to merge

**Review by devAmlan — APPROVED** [review]

**Pull request merged**
